[package]
name = "igd"
version = "0.6.0"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
homepage = "https://github.com/SBSTP/rust-igd"
repository = "https://github.com/SBSTP/rust-igd"
documentation = "https://sbstp.github.io/rust-igd/igd/"
readme = "README.md"
keywords = ["igd", "upnp"]
license = "MIT"

[dependencies]
regex = "0.2"
xml-rs = "0.7"
xmltree = "0.7"
rand = "0.4"

[dependencies.hyper]
version = "0.10"
default-features = false
